<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="1" total="2" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-03-31T12:26:29Z" name="Default suite" finished-at="2020-03-31T12:26:32Z" duration-ms="3012">
    <groups>
    </groups>
    <test started-at="2020-03-31T12:26:29Z" name="Default test" finished-at="2020-03-31T12:26:32Z" duration-ms="3012">
      <class name="unittest.UnitTest">
        <test-method signature="runPrototypeOne(java.lang.reflect.Method)[pri:0, instance:unittest.UnitTest@2aece37d]" started-at="2020-03-31T12:26:29Z" name="runPrototypeOne" description="This is the test created for calculating the Monthly Newspaper subscription for any given monthin any given year based on the user input" finished-at="2020-03-31T12:26:32Z" duration-ms="2968" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void unittest.UnitTest.runPrototypeOne(java.lang.reflect.Method)]]>
              </value>
            </param>
          </params>
          <exception class="com.testvagrant.testingchallenge.PrototypeOne$CustomException">
            <message>
              <![CDATA[No proper newspapers entered by user. Exiting the program. Please run again]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.testvagrant.testingchallenge.PrototypeOne$CustomException: No proper newspapers entered by user. Exiting the program. Please run again
at com.testvagrant.testingchallenge.PrototypeOne.calculateMonthlySubscriptions(PrototypeOne.java:59)
at com.testvagrant.testingchallenge.Application.runApplication(Application.java:11)
at unittest.UnitTest.runPrototypeOne(UnitTest.java:17)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- com.testvagrant.testingchallenge.PrototypeOne$CustomException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runPrototypeOne -->
      </class> <!-- unittest.UnitTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
